# Form implementation generated from reading ui file 'content.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_content_window(object):
    def setupUi(self, content_window):
        content_window.setObjectName("content_window")
        content_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=content_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setContentsMargins(-1, -1, -1, 0)
        self.main_layout.setObjectName("main_layout")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setContentsMargins(-1, -1, 0, -1)
        self.top_layout.setObjectName("top_layout")
        self.left_layout = QtWidgets.QVBoxLayout()
        self.left_layout.setObjectName("left_layout")
        self.top_layout.addLayout(self.left_layout)
        self.middle_layout = QtWidgets.QVBoxLayout()
        self.middle_layout.setContentsMargins(-1, 0, -1, 0)
        self.middle_layout.setObjectName("middle_layout")
        self.top_layout.addLayout(self.middle_layout)
        self.right_layout = QtWidgets.QVBoxLayout()
        self.right_layout.setObjectName("right_layout")
        self.top_layout.addLayout(self.right_layout)
        self.top_layout.setStretch(1, 3)
        self.main_layout.addLayout(self.top_layout)
        self.bottom_layout = QtWidgets.QVBoxLayout()
        self.bottom_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.bottom_layout.setObjectName("bottom_layout")
        self.main_layout.addLayout(self.bottom_layout)
        self.main_layout.setStretch(0, 6)
        self.verticalLayout_2.addLayout(self.main_layout)
        content_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=content_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        content_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=content_window)
        self.statusbar.setObjectName("statusbar")
        content_window.setStatusBar(self.statusbar)

        self.retranslateUi(content_window)
        QtCore.QMetaObject.connectSlotsByName(content_window)

    def retranslateUi(self, content_window):
        _translate = QtCore.QCoreApplication.translate
        content_window.setWindowTitle(_translate("content_window", "MainWindow"))
