# Form implementation generated from reading ui file 'project_self_check.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_project_self_check_window(object):
    def setupUi(self, project_self_check_window):
        project_self_check_window.setObjectName("project_self_check_window")
        project_self_check_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=project_self_check_window)
        self.centralwidget.setObjectName("centralwidget")
        project_self_check_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=project_self_check_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        project_self_check_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=project_self_check_window)
        self.statusbar.setObjectName("statusbar")
        project_self_check_window.setStatusBar(self.statusbar)

        self.retranslateUi(project_self_check_window)
        QtCore.QMetaObject.connectSlotsByName(project_self_check_window)

    def retranslateUi(self, project_self_check_window):
        _translate = QtCore.QCoreApplication.translate
        project_self_check_window.setWindowTitle(_translate("project_self_check_window", "程序自检"))
