# Form implementation generated from reading ui file 'project_self_check_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_project_self_check_dialog(object):
    def setupUi(self, project_self_check_dialog):
        project_self_check_dialog.setObjectName("project_self_check_dialog")
        project_self_check_dialog.resize(591, 485)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=project_self_check_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 440, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(project_self_check_dialog)
        self.buttonBox.accepted.connect(project_self_check_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(project_self_check_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(project_self_check_dialog)

    def retranslateUi(self, project_self_check_dialog):
        _translate = QtCore.QCoreApplication.translate
        project_self_check_dialog.setWindowTitle(_translate("project_self_check_dialog", "程序自检"))
